__future__          ast                 formatter           random
_ast                astroid             fractions           re
_ast27              asynchat            ftplib              reprlib
_ast3               asyncio             functools           rlcompleter
_asyncio            asyncore            gc                  runpy
_bisect             atexit              genericpath         sched
_blake2             audioop             getopt              secrets
_bootlocale         base64              getpass             select
_bz2                bdb                 gettext             selectors
_codecs             binascii            glob                setuptools
_codecs_cn          binhex              gzip                shelve
_codecs_hk          bisect              hashlib             shlex
_codecs_iso2022     brain_argparse      heapq               shutil
_codecs_jp          brain_attrs         hmac                signal
_codecs_kr          brain_builtin_inference html                site
_codecs_tw          brain_collections   http                six
_collections        brain_curses        idlelib             smtpd
_collections_abc    brain_dateutil      imaplib             smtplib
_compat_pickle      brain_fstrings      imghdr              sndhdr
_compression        brain_functools     imp                 socket
_csv                brain_gi            importlib           socketserver
_ctypes             brain_hashlib       inspect             sqlite3
_ctypes_test        brain_io            io                  sre_compile
_datetime           brain_mechanize     ipaddress           sre_constants
_decimal            brain_multiprocessing isort               sre_parse
_distutils_findvs   brain_namedtuple_enum itertools           ssl
_dummy_thread       brain_nose          json                stat
_elementtree        brain_numpy         keyword             statistics
_functools          brain_pkg_resources lazy_object_proxy   string
_hashlib            brain_pytest        lib2to3             stringprep
_heapq              brain_qt            linecache           struct
_imp                brain_random        locale              subprocess
_io                 brain_re            logging             sunau
_json               brain_six           lzma                symbol
_locale             brain_ssl           macpath             symtable
_lsprof             brain_subprocess    macurl2path         sys
_lzma               brain_threading     mailbox             sysconfig
_markupbase         brain_typing        mailcap             tabnanny
_md5                brain_uuid          marshal             tarfile
_msi                builtins            math                telnetlib
_multibytecodec     bz2                 mccabe              tempfile
_multiprocessing    cProfile            mimetypes           test
_opcode             calendar            mmap                textwrap
_operator           certifi             modulefinder        this
_osx_support        cgi                 msilib              threading
_overlapped         cgitb               msvcrt              time
_pickle             chunk               multiprocessing     timeit
_pydecimal          cmath               netrc               tkinter
_pyio               cmd                 nntplib             token
_random             code                nt                  tokenize
_sha1               codecs              ntpath              trace
_sha256             codeop              nturl2path          traceback
_sha3               collections         numbers             tracemalloc
_sha512             colorama            opcode              tty
_signal             colorsys            operator            turtle
_sitebuiltins       compileall          optparse            turtledemo
_socket             concurrent          os                  typed_ast
_sqlite3            configparser        parser              types
_sre                contextlib          pathlib             typing
_ssl                copy                pdb                 unicodedata
_stat               copyreg             pickle              unittest
_string             crypt               pickletools         urllib
_strptime           csv                 pip                 uu
_struct             ctypes              pipes               uuid
_symtable           curses              pkg_resources       venv
_testbuffer         datetime            pkgutil             warnings
_testcapi           dbm                 platform            wave
_testconsole        decimal             plistlib            weakref
_testimportmultiple difflib             poplib              webbrowser
_testmultiphase     dis                 posixpath           wheel
_thread             distutils           pprint              wincertstore
_threading_local    doctest             profile             winreg
_tkinter            dummy_threading     pstats              winsound
_tracemalloc        easy_install        pty                 wrapt
_warnings           email               py_compile          wsgiref
_weakref            encodings           pyclbr              xdrlib
_weakrefset         ensurepip           pydoc               xml
_winapi             enum                pydoc_data          xmlrpc
abc                 errno               pyexpat             xxsubtype
aifc                faulthandler        pygame              zipapp
antigravity         filecmp             pylint              zipfile
argparse            fileinput           queue               zipimport
array               fnmatch             quopri              zlib